### ISSUE TITLE
未知原因，tg bot 执行 /sub 后卡死

### ISSUE THREAD

**Issue by Matcha-sama** [pureink/inkrss#1]
其它指令无响应
（希望开发者能推出server版

**Comment by pureink** [comment]
> 其它指令无响应
> 
> （希望开发者能推出server版

1. 是否成功部署，并设定了webhook呢？
2. /sub卡死的具体表现是什么呢，可以提供相关截图么？网页是否可以正常订阅呢
3. 不会考虑部署在服务器，inkrss的初衷和特点是无服务器。我认为这减少了部署和管理的难度并且免费。服务器部署推荐使用https://github.com/indes/flowerss-bot或者https://github.com/iovxw/rssbot

**Comment by Matcha-sama** [comment]
成功部署，设定webhook
/sub 后，所有指令都不回复，网页正常订阅

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by pureink** [comment]
抱歉，尝试复现无果，无法排除是配置问题，如不介意可将代码压缩发送至我的邮箱 pureink@tutanota.com 建议检查配置，以及webhook设定路径是否正确
