### ISSUE TITLE
rss是否可以增加 支持修改网页title 或者TG机器人支持添加标签

### ISSUE THREAD

**Issue by huoshenw** [pureink/inkrss#10]

**Comment by pureink** [comment]
如果自动根据源标题生成对应的hashtag可能会因为标题含有一些特殊字符而无法显示正常，比如“-”或者空格。如果根据用户输入自行决定标题或hashtag势必会增加配置和使用的难度。如果有强烈的需求可以考虑修改notifications文件夹下的telegram.js 将标题简单处理一下即可。例如下面函数可以去除所有非中英文和数字的字符。
```
function hashtag(str) {
    return '#' + str.replace(/[^\u4E00-\u9FA50-9a-zA-Z_]/g, '')
}
```

**Comment by hjm7** [comment]
我想添加rsshub同一站点的不同内容，结果只能订阅一个，第二个根本订阅不了，提示已经订阅，不能改title没办法用啊
