### ISSUE TITLE
运行一段时间后，提示这个错误。麻烦帮忙定位一下是哪里出错了。

### ISSUE THREAD

**Issue by kugooer** [pureink/inkrss#12]
"outcome": "exception",
  "scriptName": null,
  "exceptions": [
    {
      "name": "Error",
      "message": "Network connection lost.",
      "timestamp": 1631248888441
    }
  ],
  "logs": [
    {
      "message": [
        "error over max start notify"
      ],
      "level": "log",
      "timestamp": 1631248842438
    }
  ],
  "eventTimestamp": 1631248796071,
  "event": {
    "cron": "*/1 * * * *",
    "scheduledTime": 1631248795000
  },
  "id": 20
}

**Comment by pureink** [comment]
社区里也有人最近遇到了类似的问题 https://community.cloudflare.com/t/worker-throws-network-connection-lost/287314 暂时还没有解决方案。从字面意思网络连接丢失考虑，可能是cloudflare worker的问题。

**Comment by pureink** [comment]
问题已被修复
