### ISSUE TITLE
完善微信推送功能: 添加内容的推送以及转义字符处理.

### ISSUE THREAD

**Issue by OrangeX4** [pureink/inkrss#16]
微信推送部分的代码写得比较简陋, 也许可以更新一下.

原来的代码是:

``` javascript
await fetch(`${config.WECHAT_URL}&msg_type=text&msg=${feed.title}\n${item.title}\n${item.link}`)
```

只有标题和链接 没有内容 `item.contentSnippet`.

并且存在 bug: 标题中可能存在需要转义的字符, 如 `&`. 如果有一个标题中含有 `&` 就会被中途截断. 推荐使用 `encodeURI(text)` 函数进行转义处理.

我修改之后的代码为:

``` javascript
if (item.contentSnippet) {
    await fetch(`${config.WECHAT_URL}&msg_type=text&msg=${encodeURI(feed.title)}\n---------------------------------------\n${encodeURI(item.title)}\n\n${encodeURI(item.contentSnippet)}\n\nLink: ${encodeURI(item.link)}`);
} else {
    await fetch(`${config.WECHAT_URL}&msg_type=text&msg=${encodeURI(feed.title)}\n---------------------------------------\n${encodeURI(item.title)}\n\nLink: ${encodeURI(item.link)}`);
}
```

这段代码也许有一定的参考意义. 没有提 PR 是因为我不清楚这种格式以及处理的方法是否能被接受, 具体的代码修改还是作者来修改比较好.

**Comment by pureink** [comment]
感谢建议，bark的代码中我进行了转义，但微信中疏忽忘记了，会尽快修改。但对于content我认为仍然不值得添加，在telegram中提供链接会有预览，开启telegraph选项后更有即时预览可以提供内容。微信由于接口限制只能发送纯文本，而内容大部分为html，即使加以处理也很难获得良好的阅读体验，文本长度也可能会超出限制。标题，更新内容的标题，以及链接已经很好的提供了通知的功能，因此不考虑加入更新的内容（即使在telegram中这也只是个可选项，并默认关闭）

**Comment by OrangeX4** [comment]
好的，感谢回复，这个 issue 我就 close 了。
