### ISSUE TITLE
Error! can't parse this url

### ISSUE THREAD

**Issue by scramjetFoam** [pureink/inkrss#17]
您好，我部署成功了，但是订阅时无法解析feed，我是使用模版自己搭建的，选的private，url填写的https://inkrss-shangwangnust.vercel.app/，不知道哪里出错了。我以前没接触过这种，所以不知道如何排查错误。谢谢，打扰了。

**Comment by pureink** [comment]
我这里测试了一下您提供的链接 https://inkrss-shangwangnust.vercel.app 发现并不能使用，请问是否成功部署了呢？还有“我是使用模版自己搭建的，选的private”指的是vercel部署的函数么？订阅时无法解析应该只有两种可能，一个是配置的PARSE_URL错误，一个是订阅源有问题。不如先尝试将PARSE_URL替换为我部署的 https://inkrssparse.vercel.app 试试吧。

**Comment by ShangWangNUST** [comment]
您好，我刚刚把部署的删除了，所以可能无法访问。附件（最后）是我重新部署收到的邮件。我不知道选用哪个URL
private是在vercel部署时，建立的git库我选的private，我不知道是不是这个原因无法访问，所以删了建立了一个public的。
我现在先试下您的公开接口。

Successfully deployed to the following URLs:

inkrss-zhbe – ./

inkrss-zhbe.vercel.app
inkrss-zhbe-shangwangnust.vercel.app
inkrss-zhbe-git-main-shangwangnust.vercel.app

**Comment by pureink** [comment]
以上三个链接均可以使用，但这和您刚才提供的 https://inkrss-shangwangnust.vercel.app 并不相同。使用以上三个链接应该可以正常部署。git仓库无论设定为private还是public都没有影响。

**Comment by scramjetFoam** [comment]
谢谢您的解答。目前已经成功订阅了，经排查是无法解析这个rss源（https://www.daniao.org/feed/），我试了少数派和其他的就可以。
