### ISSUE TITLE
大佬，已部署的想要更新怎么操作啊

### ISSUE THREAD

**Issue by beer-on-ice** [pureink/inkrss#21]
部署了很久了，最近看到你这边代码有更新，怎么操作更新最快捷啊

**Comment by pureink** [comment]
到目前为止的更新大多是修复之前的错误，如果使用没有发现问题可以选择不更新。
更新的话，因为现在和将来都不会频繁发生，还是推荐从头部署一遍。

**Comment by beer-on-ice** [comment]
好，了解谢谢
