### ISSUE TITLE
SECRET_PATH 如何填寫呢 找不到...

### ISSUE THREAD

**Issue by brokerplaform** [pureink/inkrss#22]
![image](https://user-images.githubusercontent.com/73445419/147408655-547007d9-1880-42d1-9848-67905c89df45.png)

**Comment by pureink** [comment]
随便编一串 比如abc，123但只能用字母和数字。用处是隐藏网页的路径，部署后在xxx.workers.dev/abc进行操作

**Comment by brokerplaform** [comment]
感謝 我找到了  想了老半天  原來是''自訂訂閱網址''的意思
