### ISSUE TITLE
vercel部署失败

### ISSUE THREAD

**Issue by debeetle** [pureink/inkrss#23]
vercel一键部署都失败，卡在第一步

**Comment by pureink** [comment]
vercel部署的仅有云函数用于解析xml文件，并不提供前端页面，能否提供部署失败的具体截图呢

**Comment by debeetle** [comment]
很抱歉我并没有在vercel找到任何具体报错信息，只是如图说失败

<img width="663" alt="Screen Shot 2022-02-12 at 00 16 36" src="https://user-images.githubusercontent.com/62332122/153628618-04e5a8bb-b06d-4c6c-b079-e200f08f6aa5.png">

另外github显示仓库克隆失败，并且我注意到似乎自动克隆的路径 pureink/inkrss/parse内的文件引用了外部一些文件，不知道是否有关系

<img width="1376" alt="Screen Shot 2022-02-12 at 00 17 17" src="https://user-images.githubusercontent.com/62332122/153629243-adf9501a-8346-4c04-9324-f4b2923e7c7c.png">

我的解决办法是手动克隆并部署，昨天已成功运行，并且将bark的通知改成一个新项目https://github.com/easychen/pushdeer 也有效。
由于本人代码能力薄弱，如有不妥还请见谅
