### ISSUE TITLE
> 如果还有问题随时提issue就好。

### ISSUE THREAD

**Issue by sudojia** [pureink/inkrss#3]
> 如果还有问题随时提issue就好。

很抱歉我又打开这条 issues 了
关于部署之后我已设置 webhook，机器人也回复了一句 “请输入格式正确的订阅源”

![image](https://user-images.githubusercontent.com/86390796/127283368-dcd7d9d1-30ae-401a-8af5-ebe3cbf8aa75.png)

随后在机器人发送那些指令却没有响应

![image](https://user-images.githubusercontent.com/86390796/127283844-19594303-641f-48e3-b57c-79f7d4111a1e.png)

而网页是可以正常订阅

![image](https://user-images.githubusercontent.com/86390796/127283675-93c0fe23-5d39-4777-99dc-1f98564a1633.png)

_Originally posted by @sudojia in https://github.com/pureink/inkrss/issues/2#issuecomment-888090699_

**Comment by pureink** [comment]
webhook设定的路径是怎样的呢

**Comment by pureink** [comment]
应该不是设置问题，是函数没有正常的处理请求。是否介意将代码发送到我邮箱呢，我个人使用正常无法复现。pureink@tutanota.com

**Comment by sudojia** [comment]
> webhook设定的路径是怎样的呢

这个我不太清楚，我是访问了 `https://api.telegram.org/bot<your token>/setwebhook?url=https://example.com/secret_path` 

随后在 BotFather 那里添加了四个指令

![image](https://user-images.githubusercontent.com/86390796/127288951-0565aec4-eb76-4ea1-9462-2f225e1b761d.png)


貌似有个 BUG，就是我在网页上订阅了，测试并开启 TG 通知了，然后能推送到，就是会一直重复的三十多条了

![image](https://user-images.githubusercontent.com/86390796/127288399-982411c7-7b40-46d5-a80a-adc2d84c7cd5.png)

![image](https://user-images.githubusercontent.com/86390796/127288472-6f7d1de8-651c-4929-9039-910f7e5f3b50.png)

然后我在网页上把该订阅删了，但他还是会推送，一刷新网页，订阅又出来了（图一是删除成功的，图二是又推送到 TG 之后再刷新网页又出来了。。。）

![image](https://user-images.githubusercontent.com/86390796/127288646-706b08e3-6cfd-4945-a4c0-6bc3e3d4e1d6.png)

![image](https://user-images.githubusercontent.com/86390796/127288851-ce401752-c69f-4cdb-81e7-8849c0b1cabd.png)

**Comment by pureink** [comment]
抱歉，是bot的代码有一点逻辑问题，可以先删除部署的worker和kv，由于bot订阅失败会反复执行所以更新后没法成功修改KV，稍等我修改一下bot的代码重新部署即可。

**Comment by sudojia** [comment]
> 抱歉，是bot的代码有一点逻辑问题，可以先删除部署的worker和kv，由于bot订阅失败会反复执行所以更新后没法成功修改KV，稍等我修改一下bot的代码重新部署即可。

好的

**Comment by pureink** [comment]
非常抱歉，是我粗心了，问题已经修复。麻烦克隆最新版本进行部署，重复发送的问题应该也不会出现了。

**Comment by sudojia** [comment]
> 非常抱歉，是我粗心了，问题已经修复。麻烦克隆最新版本进行部署，重复发送的问题应该也不会出现了。

好的，没事，我再试试

**Comment by pureink** [comment]
由于部署有延迟，新部署和和旧部署的会同时存在一段时间，建议彻底删除，创建新KV进行部署

**Comment by sudojia** [comment]
> 由于部署有延迟，新部署和和旧部署的会同时存在一段时间，建议彻底删除，创建新KV进行部署

ok，感谢提醒！

**Comment by sudojia** [comment]
> 非常抱歉，是我粗心了，问题已经修复。麻烦克隆最新版本进行部署，重复发送的问题应该也不会出现了。

已经完美成功部署了，最后非常感谢大佬的项目

![image](https://user-images.githubusercontent.com/86390796/127297074-7394bc1f-3c51-456f-945d-413d46fc98c9.png)

**Comment by pureink** [comment]
也感谢你帮助发现问题，有问题记得及时反馈哦
