### ISSUE TITLE
使用wechat的方式部署失败

### ISSUE THREAD

**Issue by zytomorrow** [pureink/inkrss#4]
使用推送方式为wechat，部署失败。
![image](https://user-images.githubusercontent.com/16175551/127516271-cc728fc7-d780-4733-81da-274f32718346.png)

**Comment by zytomorrow** [comment]
配置文件如下
![image](https://user-images.githubusercontent.com/16175551/127521786-3e8077f3-0e82-4ef6-ab3b-42cfaafa99c5.png)

**Comment by pureink** [comment]
抱歉，是我的问题，应该已经修复。配置文件没有问题，麻烦再尝试一次。

**Comment by zytomorrow** [comment]
thx，已部署完成~

**Comment by pureink** [comment]
我一直没使用微信，微信这里没有用心维护，刚发现通知功能应该有问题，应该接受不到通知，会尽快修复。

**Comment by zytomorrow** [comment]
确实。刚验证了接受不到通知，我也去看看源码

**Comment by pureink** [comment]
只是拼接字符串的问题，现在应该已经修复了，我再多测试一些微信相关的东西。

**Comment by pureink** [comment]
应该没有问题了，不过再次部署可能需要一段时间生效，之后才会定时运行任务。

**Comment by zytomorrow** [comment]
好的，thx
