### ISSUE TITLE
大部分wordpress站点的订阅源文本不规范导致订阅报错

### ISSUE THREAD

**Issue by caonimarss** [pureink/inkrss#7]
挖站否-挖掘建站的乐趣
连续多次失败，将暂停更新，请检查订阅源是否正常。
小俊博客 - 一个从小对网络感兴趣的男孩子
连续多次失败，将暂停更新，请检查订阅源是否正常。
例如这两个:
https://wzfou.com/feed/
https://www.xjisme.com/feed
请问有什么办法强制拉取更新吗?

**Comment by pureink** [comment]
测试了一下两个站点解析都正常,不过在解析之前会先判断更新。第二个站点xml文件在开头有一些空格导致判断错误，这一部分我会最近做出修改，可以被解决。
第一个端点失败的原因我还不能完全确定，我在本地测试时甚至是正常的。初步猜想是站点的防御措施，可以考虑在wrangler.toml中修改cron trigger的间隔，默认是每分钟获取一次，也可能是其他网络原因造成的访问失败，此类情况可以修改config.js中maxerrortimes。

**Comment by pureink** [comment]
已修复

**Comment by caonimarss** [comment]
好的,谢谢大佬,请问能加个TG吗?想要讨论一下例如自己网站开启CF五秒护盾情况下,使用大佬你的这个项目进行RSS订阅

**Comment by caonimarss** [comment]
大佬这是我的邮箱:caonimarss@outlook.com

**Comment by pureink** [comment]
我认为既然开盾了也没有必要进行订阅给源站造成压力了。最近几个月比较忙，有问题在这里讨论就好，会不定时回复。
