### ISSUE TITLE
我部署以后访问了网站 显示成功 但是TG中不显示即时预览

### ISSUE THREAD

**Issue by huoshenw** [pureink/inkrss#9]
![图片](https://user-images.githubusercontent.com/26380831/130632866-26c1180f-a648-463f-8d45-b0b114a5a553.png)

**Comment by pureink** [comment]
网页中表格第三列为开启即时预览的按钮，如确认开启 可能是源没有提供内容

**Comment by huoshenw** [comment]
开启了
![图片](https://user-images.githubusercontent.com/26380831/130635326-422cd693-57f9-4767-9f61-5a17fcf77c65.png)

![图片](https://user-images.githubusercontent.com/26380831/130635065-2e5589f1-32eb-4f64-a75b-1473babab3de.png)
其他的rss有提供内容
![图片](https://user-images.githubusercontent.com/26380831/130635198-e09023b4-035b-4bc5-8534-df50f45d3bf4.png)
![图片](https://user-images.githubusercontent.com/26380831/130635217-e72fc223-c921-4d21-8f9f-3a00a861da8f.png)

**Comment by pureink** [comment]
应该是源没提供内容 可以把链接发出来参考一下

**Comment by huoshenw** [comment]
https://rssfeed.today/weibo/rss/2634877355

**Comment by pureink** [comment]
目前这类短内容我认为没有即时预览的必要，因此只有长文章会出现即时预览。这部分如果认为有需求的话我可以修改一下，是否需要修改呢？

**Comment by huoshenw** [comment]
额我的需求就是抓取微博的 麻烦大佬修改一下 或者提供一个可选项也好

**Comment by huoshenw** [comment]
而且这类rss的抓取频率一直有延迟半小时以上不知道是什么问题

**Comment by pureink** [comment]
有延迟一般都是源的问题，如果源没能及时更新每秒抓取一次也没意义。

**Comment by pureink** [comment]
刚刚进行了一下测试，虽然极个别内容不会提供即时预览，但您的链接我测试相当正常。![image](https://user-images.githubusercontent.com/44235276/130642557-8474a5fb-dce9-45a8-a0fd-b3c2d868dd84.png)
是否部署了最新版本并且提供了正确的telegraph token呢
